# services.yml
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: inhabit
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: inhabit
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

